# Assetic Configuration
assetic:
    assets:
        open_sans_light_woff:
            input: %kernel.root_dir%/../web/dist/assets/fonts/google/open-sans-light.woff
            output: dist/assets/fonts/google/open-sans-light.woff
        open_sans_semibold_woff:
            input: %kernel.root_dir%/../web/dist/assets/fonts/google/open-sans-semibold.woff
            output: dist/assets/fonts/google/open-sans-semibold.woff
        glyphicons_halflings_regular_woff2:
            input: %kernel.root_dir%/../web/dist/assets/fonts/glyphicons/glyphicons-halflings-regular.woff2
            output: dist/assets/fonts/glyphicons/glyphicons-halflings-regular.woff2
        fontawesome_webfont_woff2:
            input: %kernel.root_dir%/../web/dist/assets/fonts/font-awesome/fontawesome-webfont.woff2
            output: dist/assets/fonts/font-awesome/fontawesome-webfont.woff2
        main_bundle_js:
            input: %kernel.root_dir%/../web/dist/main.bundle.js
            output: dist/main.bundle.js
                    
        
         
         
