imports:
    - { resource: config_test.yml }

framework:
    profiler:
        only_exceptions: false
        collect: true     

web_profiler:
    toolbar: true 
    
csa_guzzle:
    logger: true
    clients:
        local_test_api:
            config:
                base_url: http://imperya/app_acceptance.php/    

