services:
#    pay_pay.example:
#        class: Multiservices\PayPayBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]
    paypaybundle.form.handler.ingresos:
       class: AppBundle\Form\Handler\FormHandler
       arguments: ["@doctrine.orm.entity_manager","@form.factory","@paypaybundle.form.ingresostype"]
    paypaybundle.form.ingresostype:
        class: Multiservices\PayPayBundle\Form\IngresosType
    paypaybundle.form.handler.facturas:
       class: AppBundle\Form\Handler\FormHandler
       arguments: ["@doctrine.orm.entity_manager","@form.factory","@paypaybundle.form.facturastype"]
    paypaybundle.form.facturastype:
        class: Multiservices\PayPayBundle\Form\FacturasType    
        
    paypay.form.type.formasPagos:
        class: Multiservices\PayPayBundle\Form\Type\FormasPagosType
        arguments: ["@doctrine.orm.entity_manager"]
        tags:
            - { name: form.type, alias: formasPagos }
    paypaybundle_datatable.ingresos:
        class: Multiservices\PayPayBundle\Datatables\IngresosDatatable
        tags:
            - { name: sg.datatable.view }            
    paypaybundle_datatable.egresos:
        class: Multiservices\PayPayBundle\Datatables\EgresosDatatable
        tags:
            - { name: sg.datatable.view }  