services:
#    arxis_contable.example:
#        class: Arxis\ContableBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]
    arxiscontablebundle.form.handler.contacto:
       class: AppBundle\Form\Handler\FormHandler
       arguments: ["@doctrine.orm.entity_manager","@form.factory","@arxiscontablebundle.form.contactotype"]
    arxiscontablebundle.form.contactotype:
        class: Arxis\ContableBundle\Form\ContactoType    