services:
#    arxis_contable.example:
#        class: Arxis\ContableBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]
    contablebundle.form.handler.facturas:
       class: AppBundle\Form\Handler\FormHandler
       arguments: ["@doctrine.orm.entity_manager","@form.factory","@contablebundle.form.facturastype"]
    contablebundle.form.facturastype:
        class: Arxis\ContableBundle\Form\ContactoType    